# theme_park_dbt/models/staging/sources.yml
version: 2

sources:
  - name: raw
    # BigQuery: database = GCP project, schema = dataset
    database: "{{ env_var('GCP_PROJECT') }}"
    schema: raw
    tables:
      - name: raw_wait_times
      - name: raw_forecast
      - name: raw_weather
